spring:
  datasource:
    name: ems
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: Software@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
